package cssfd;

import java.awt.print.PrinterException;
import java.util.*;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jester
 */
public class print extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public print() {
        initComponents();
    }
    
    String sub;
    String pay;
    String bal;
    
     public print(String sub, String pay, String bal, TableModel tableModel) throws PrinterException {
        initComponents();
        
        this.sub = sub;
        this.pay = pay;
        this.bal = bal;
        
        
        txtreceipt.setText(txtreceipt.getText()+ "================================================\n");
        txtreceipt.setText(txtreceipt.getText()+ "============== HEFFLOX AUTO-SUPPLY ==============\n");
        txtreceipt.setText(txtreceipt.getText()+ "================================================\n");
        txtreceipt.setText(txtreceipt.getText()+ "============== Address: Malvar, Batangas ==============\n");
        txtreceipt.setText(txtreceipt.getText()+ "================================================\n");
        
        
        for(int i = 0; i<tableModel.getRowCount(); i++)
        {
            String make = (String) tableModel.getValueAt(i,1);
            String model = (String) tableModel.getValueAt(i,2);
            String price = (String) tableModel.getValueAt(i,3);
            int total = (int) tableModel.getValueAt(i,5);
            
            txtreceipt.setText(txtreceipt.getText()+ "       DESCRIPTION                                                           ITEM\n");
            txtreceipt.setText(txtreceipt.getText()+ "\n");
            txtreceipt.setText(txtreceipt.getText()+ "             Make                                                                    "+ make);
            txtreceipt.setText(txtreceipt.getText()+ "\n");
            txtreceipt.setText(txtreceipt.getText()+ "             Model                                                                   "+ model);
            txtreceipt.setText(txtreceipt.getText()+ "\n");
            txtreceipt.setText(txtreceipt.getText()+ "             Price                                                                       "+ price);
            txtreceipt.setText(txtreceipt.getText()+ "\n");
            txtreceipt.setText(txtreceipt.getText()+ "             Total                                                                        "+ total);
        }
        txtreceipt.setText(txtreceipt.getText()+ "\n");
        txtreceipt.setText(txtreceipt.getText()+ "--------------------------------------------------------------------------------------\n");
        
        
        txtreceipt.setText(txtreceipt.getText()+ "             SubTotal  :                                                              "+ sub);
        txtreceipt.setText(txtreceipt.getText()+ "\n");
        txtreceipt.setText(txtreceipt.getText()+ "             Pay         :                                                              "+ pay);
        txtreceipt.setText(txtreceipt.getText()+ "\n");
        txtreceipt.setText(txtreceipt.getText()+ "             Change   :                                                              "+ bal);
        txtreceipt.setText(txtreceipt.getText()+ "\n");
        
        
        txtreceipt.setText(txtreceipt.getText()+ "================================================\n");
        txtreceipt.setText(txtreceipt.getText()+ "=============== Thank You for Shopping! ==============\n");
        txtreceipt.setText(txtreceipt.getText()+ "================================================\n");
        
        
        txtreceipt.print();
        
    }
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtreceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtreceipt.setColumns(20);
        txtreceipt.setRows(5);
        jScrollPane1.setViewportView(txtreceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtreceipt;
    // End of variables declaration//GEN-END:variables
}
